consul:
  command: -server -bootstrap -advertise 172.17.0.1
  image: gliderlabs/consul-server:latest
  ports:
    - "8400:8400"
    - "8500:8500"
    - "172.17.0.1:53:8600/udp"

registrator:
  command: -ip 172.17.0.1 consul://consul:8500
  image: gliderlabs/registrator:latest
  links:
    - consul
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

geoserver:
  image: jwiii/elasticgeo:2.8.1-RC1
  dns:
    - "172.17.0.1"
  dns_search:
    - "service.consul"
  ports:
    - "8080:8080"
  links:
    - elastic
  environment:
    SERVICE_NAME: geoserver
    SERVICE_TAGS: gis,wms,wfs,imagery
    SERVICE_CHECK_HTTP: /
    SERVICE_CHECK_INTERVAL: 15s
    SERVICE_CHECK_TIMEOUT: 1s

elastic:
  image: elasticsearch:2.2.0
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    SERVICE_NAME: elasticsearch
    SERVICE_TAGS: search,gis
    SERVICE_CHECK_TCP: "true"
    SERVICE_CHECK_INTERVAL: 15s
    SERVICE_CHECK_TIMEOUT: 1s
